# Generated by Django 4.0.5 on 2022-06-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='authprovider',
            field=models.CharField(default='e', max_length=1),
        ),
    ]
